spring:
  application:
    name: userservice

jwt:
  secret: ${JWT_SECRET}

userservice:
  internal-endpoint-secret: ${USERSERVICE_INTERNAL_ENDPOINT_SECRET}

internal:
  ttl-seconds: ${INTERNAL_TTL_SECONDS:60}
